config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('result/', views.result, name='result'),
    path('addQuestion/', views.addQuestion, name='addQuestion'),
    path('add/', views.add, name='add'),
]


app_name = 'polls'

polls/models.py
from bs4 import BeautifulSoup
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    proportion = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from bs4 import BeautifulSoup
from polls.models import Question, Choice
from django.utils import timezone

def main(request):
    return render(request, 'polls/main.html')

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def result(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]

    for q in latest_question_list:
        total = 0
        choice = Choice.objects.all().filter(question = q)

        for c in choice:
            total += c.votes

        for c in choice:
            c.proportion = round(c.votes / total * 100)
            c.save()

    context = {'questions': latest_question_list}
    return render(request, 'polls/result.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    cho_id = request.POST.get('choice')
    choice = get_object_or_404(Choice, pk=cho_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:index'))

def addQuestion(request):
    return render(request, 'polls/addQuestion.html')

def add(request):
    question = request.POST.get('question')
    choice1 = request.POST.get('choice1')
    choice2 = request.POST.get('choice2')

    q = Question(question_text=question, pub_date=timezone.now())
    q.save()

    c = Choice(question=q, choice_text=choice1)
    c.save()
    c = Choice(question=q, choice_text=choice2)
    c.save()

    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/addQuestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Today</title>
    <style>
        body{
            background-color:#f9e0ae;
            text-align:center;
        }
    </style>
</head>
<body>
    <form action="{% url 'polls:add'%}" method="post">
        {% csrf_token %}
        질문<br>
        <input type="text" name="question"><br>
        선택지<br>
        <input type="text" name="choice1"><br>
        <input type="text" name="choice2"><br>

        <input type="submit" value="등록하기">
    </form>

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Today</title>
    <style>
        body{
            background-color:#f9e0ae;
            color:#682c0e;
            text-align:center;
        }
    </style>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">{% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Today</title>
    <style>
        body{
            background-color:#f9e0ae;
            text-align:center;
        }
        li{
            list-style:none;
            font-size:40px;s
        }
        a{
            text-decoration:none;
            color:#682c0e;
        }
    </style>
</head>
<body>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <a href="{% url 'polls:result' %}">결과확인</a><br>
    <a href="{% url 'polls:addQuestion' %}">질문추가하기</a>
</body>
</html>

polls/templates/polls/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Today</title>
    <style>
        body{
            background-color:#f9e0ae;
            text-align:center;
        }
        h1{
            color:#FCA205;
            font-size:50px;
        }
        a{
            text-decoration:none;
            color:#682c0e;
        }
    </style>
</head>
<body>
    <h1>오늘의 기분</h1>
    <a href="{% url 'polls:index' %}">시작</a>
</body>
</html>

polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Today</title>
    <style>
        body{
            background-color:#f9e0ae;
            text-align:center;
        }
        h1{
            color:#fc8621
        }
        .proportion{
            color: #c24914
        }
        li{
            list-style:none;
        }
    </style>
</head>
<body>
    <h1>결과</h1>
    {% for question in questions %}
        <div>
            {{question.question_text}}<br>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li>{{choice.choice_text}} : <span class="proportion">{{choice.proportion}}%</span></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
</body>
</html>